命令稿啟動於 2017年03月11日 (週六) 16時08分40秒
]0;mkl@mkl-VirtualBox: ~[01;32mmkl@mkl-VirtualBox[00m:[01;34m~[00m$ whoami; pwd
mkl
/home/mkl
]0;mkl@mkl-VirtualBox: ~[01;32mmkl@mkl-VirtualBox[00m:[01;34m~[00m$ git cong[Kfig -l
user.name=MrMKL
user.email=jasonma_0803@Hotmail.com
]0;mkl@mkl-VirtualBox: ~[01;32mmkl@mkl-VirtualBox[00m:[01;34m~[00m$ git clone https://github.com/MrMKL/b[Klab1.git
Cloning into 'lab1'...
warning: You appear to have cloned an empty repository.
Checking connectivity... done.
]0;mkl@mkl-VirtualBox: ~[01;32mmkl@mkl-VirtualBox[00m:[01;34m~[00m$ exit

命令稿已於 2017年03月11日 (週六) 16時09分44秒
 完成